backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "index"
    label: "Home Page"
    files:
      - name: "index"
        label: "Index Page"
        file: "src/pages/index.md"
        fields:
          - { name: "path", label: "Path", widget: "string" }
          - { name: "heading", label: "Heading", widget: "string" }
          - { name: "backgroundVideo", label: "Background Video", widget: "file" }
          - name: "tiles"
            label: "Tiles"
            widget: "list"
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "path", label: "Path", widget: "string" }
              - { name: "image", label: "Image", widget: "image" }
          - name: "summary"
            label: "Summary"
            widget: "text"
          - { name: "clientLabel", label: "Client Label", widget: "string" }
          - name: "clients"
            label: "Clients"
            widget: "list"
            fields:
              - { name: "name", label: "Name", widget: "string" }
              - { name: "link", label: "Link", widget: "string" }
              - { name: "logo", label: "Logo", widget: "image" }
          - name: "testimonials"
            label: "Testimonials"
            widget: "list"
            fields:
              - { name: "body", label: "Body", widget: "text" }
              - { name: "name", label: "Name", widget: "string" }
              - { name: "company", label: "Company", widget: "string" }
